alias: ...
description: ""
triggers:
  - entity_id: [Gerät]
    attribute: current_temperature
    trigger: state
  - entity_id: [Gerät]
    attribute: temperature
    trigger: state
  - entity_id: [Gerät]
    trigger: state
  - entity_id: [Solltemperaturregler]
    trigger: state
  - entity_id: [RaumTemperaturSensor]
    trigger: state
	
	
	
conditions: []
actions:
  - alias: Heizen
    if:
      - condition: state
        entity_id: [Gerät]
        state: heat
    then:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ states('[RaumTemperaturSensor]')| float
                  <= states('[Solltemperaturregler]') | float }}
            sequence:
              - action: climate.set_temperature
                data:
                  temperature: " {{ (state_attr('[Gerät]','current_temperature')|float(19) ) }}"
                target:
                  entity_id: [Gerät]
              - action: input_boolean.turn_off
                target:
                  entity_id: [Boolean]
                data: {}
          - conditions:
              - condition: template
                value_template: >-
                  {{ states('[RaumTemperaturSensor]')| float
                  >= states('[Solltemperaturregler]') | float + 1.2}} 
            sequence:
              - action: input_boolean.turn_on
                target:
                  entity_id: [Boolean]
                data: {}
              - action: climate.set_temperature
                data:
                  temperature: "{{ 16 }}"
                target:
                  entity_id: [Gerät]
          - conditions:
              - condition: template
                value_template: "{{ states('[Boolean]') == 'off' }}"
            sequence:
              - action: climate.set_temperature
                data:
                  temperature: >-
                    {{
                    (state_attr('[Gerät]','current_temperature')|float
                    * 2 ) | int / 2  -2.0}}   
                target:
                  entity_id: [Gerät]
  - alias: Trocknen/Kühlen
    if:
      - condition: or
        conditions:
          - condition: state
            entity_id: [Gerät]
            state: dry
          - condition: state
            entity_id: [Gerät]
            state: cool
    then:
      - if:
          - condition: template
            value_template: >-
              {{ state_attr('[Gerät]', 'current_temperature') >=
              states('[Solltemperaturregler]') | float }}
        then:
          - data:
              temperature: "{{ states('[Solltemperaturregler]') | float(0) }}"
            target:
              entity_id: [Gerät]
            action: climate.set_temperature
        else:
          - data:
              temperature: "{{ state_attr('[Gerät]', 'current_temperature') }}"
            target:
              entity_id: [Gerät]
            action: climate.set_temperature
mode: single

```
